In [2]:
import numpy

n = numpy.arange(27)


n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

Se puede tranformar tambien a un arreglo de dos dimensiones.

In [3]:
n.reshape(3, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

Tambien en un arreglo de tres dimensiones aunque es mucho menos utilizado.

In [4]:
n.reshape(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Ahora trabajaremos con OpenCV

In [5]:
import cv2

im_g = cv2.imread("c:/Users/janov/Desktop/DataEngineer-RoadMap/Python/07-Numpy/img/smallgray.png", 0)

if im_g is None:
    print("La imagen no se ha cargado correctamente. Verifica la ruta del archivo.")
else:
    print(im_g)


[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


Indexing 

In [6]:
im_g [0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

Podemos ver la forma de la matriz igual.

In [ ]:
im_g.shape # para este caso es de: 3 filas y 5 columnas.

(3, 5)

Itereación

In [8]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


Trasponer la matriz

In [9]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


Iterar valor por valor de la matriz

In [10]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


Apilar matrices

In [12]:
ims = numpy.hstack((im_g, im_g)) # para concatenar horizontalmente
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [13]:
ims1 = numpy.vstack((im_g, im_g)) # para concatenar verticalmente
print(ims1)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


Dividir una matriz

In [16]:
lst = numpy.vsplit(ims, 3) # para dividir horizontalmente en 3 partes

lst

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)]